### ISSUE TITLE
Patch does not apply

### ISSUE THREAD

**Issue by doggukan** [DanWin/hosting#100]
Debian 10.6 x64

"==== Successfully installed LuaJIT 2.1.0-beta3 to /usr/local ====
install -d /usr/local/lib/lua//resty/core/
install -d /usr/local/lib/lua//ngx/
install -d /usr/local/lib/lua//ngx/ssl
install lib/resty/*.lua /usr/local/lib/lua//resty/
install lib/resty/core/*.lua /usr/local/lib/lua//resty/core/
install lib/ngx/*.lua /usr/local/lib/lua//ngx/
install lib/ngx/ssl/*.lua /usr/local/lib/lua//ngx/ssl/
install -d //usr/local/lib/lua//resty/lrucache
install lib/resty/*.lua //usr/local/lib/lua//resty/
install lib/resty/lrucache/*.lua //usr/local/lib/lua//resty/lrucache/
install -d //usr/local/lib/lua//resty
install lib/resty/*.lua //usr/local/lib/lua//resty
error: patch failed: src/http/modules/ngx_http_ssl_module.c:280
error: src/http/modules/ngx_http_ssl_module.c: patch does not apply"

**Comment by DanWin** [comment]
Fixed in 78a7bdf
