### ISSUE TITLE
php-qrcode requires php 7.2

### ISSUE THREAD

**Issue by doggukan** [DanWin/hosting#101]
debian 10.6 x64

chillerlan/php-qrcode[3.1.0, ..., 3.3.0] require php ^7.2 -> your php version (8.0.0-dev) does not satisfy that requirement.

tried to change composer.json to ^4.3 as seen on github repo of php-qrcode.seems like fixes the issue

**Comment by doggukan** [comment]
changed '3.1 to '4.2 .composer updated without issues.i will report back if qr code functions doesnt works

source: https://github.com/chillerlan/php-qrcode

**Comment by doggukan** [comment]
i did composer update instead of composer install thats why this happens.

**Comment by doggukan** [comment]
phpmyadmin has some issues too.

 Problem 1
    - Root composer.json requires php ^7.1.3 but your php version (8.0.0-dev) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires phpmyadmin/coding-standard ^1.0 -> satisfiable by phpmyadmin/coding-standard[1.0].
    - phpmyadmin/coding-standard 1.0 requires php ^7.1 -> your php version (8.0.0-dev) does not satisfy that requirement.
  Problem 3
    - phpmyadmin/sql-parser[5.0.0, ..., 5.4.1] require php ^7.1 -> your php version (8.0.0-dev) does not satisfy that requirement.
    - Root composer.json requires phpmyadmin/sql-parser ^5.0 -> satisfiable by phpmyadmin/sql-parser[5.0.0, ..., 5.4.1].

**Comment by DanWin** [comment]
Fixed in 777cd92a48be01247046cc125200cfa7b7580c7d

Regarding phpMyAdmin, it does seem to have an issue installing under PHP8, because the version bounds are not yet updated to 8.  As a workaround, you can use `php7.4 /usr/bin/composer install --no-dev` until it is updated.
