### ISSUE TITLE
Tor doesn't start

### ISSUE THREAD

**Issue by infoabcd** [DanWin/hosting#102]
![Screenshot_2020-11-12-19-07-49-334_com sonelli juicessh](https://user-images.githubusercontent.com/57176918/98932509-62afd500-251a-11eb-84f8-f8a6e491eea3.jpg)

**Comment by DanWin** [comment]
Looks like your server has IPv6 support disabled. Set the following sysctl config: `net.ipv6.conf.lo.disable_ipv6 = 0` e.g. by adding it to `/etc/sysctl.d/99-custom-hosting.conf` and then run `sysctl --system` to apply the changes. If you want to enable IPv6 support for all interfaces (recommended), then also add the following `net.ipv6.conf.all.disable_ipv6 = 0`

**Comment by infoabcd** [comment]
Thank you, but I have the same problem as him
https://github.com/DanWin/hosting/issues/101

**Comment by DanWin** [comment]
Hmm, also check your `/etc/default/grub` configuration (or whichever bootloader you use) for the `ipv6.disable=1` line. If it's in the configuration, remove it and reboot. Also check the output of `ifconfig` to make sure that you have an IPv6 address. If your server has to be running without IPv6 support for whatever reason, you can remove the IPv6 listening addresses from tor and use IPv4 only.

**Comment by Niendertal** [comment]
I had the same problem but solved with disable the IPV6
