### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by infoabcd** [DanWin/hosting#103]
![Screenshot_2020-11-23-20-38-57-510_com sonelli juicessh](https://user-images.githubusercontent.com/57176918/99963645-075ccd00-2dcd-11eb-8e56-110a0348f8f7.jpg)
The system is Debian Sid. Seems PHP version is too high?

**Comment by DanWin** [comment]
Fixed in 777cd92a48be01247046cc125200cfa7b7580c7d

**Comment by infoabcd** [comment]
‘php’: No such file or directory

Execution of . /install_binaries.sh with an error

**Comment by DanWin** [comment]
Can you open a new issue and post the error message you got when executing the `install_binaries.sh` ?
