### ISSUE TITLE
install_binaries.sh error

### ISSUE THREAD

**Issue by infoabcd** [DanWin/hosting#104]
‘php’: No such file or directory

Execution of . /install_binaries.sh with an error

It seems that the composer commands are in the wrong order

Although I commented out this line, it still reports an error
`curl -sSL https://github.com/composer/composer/releases/download/2.0.8/composer.phar > /usr/bin/composer && chmod +x /usr/bin/composer
composer self-update`

![Screenshot_20201224_145310](https://user-images.githubusercontent.com/57176918/103068279-c89e7a80-45f7-11eb-9104-49fc00b4c246.jpg)

**Comment by DanWin** [comment]
Fixed in 4af47d162bf8d37fd26103d06cff9dfb1de5325f
The bash script was unable to handle the glob expression `{ecdh,recovery}` so I've changed it to use the full expanded version.
