### ISSUE TITLE
composer php error

### ISSUE THREAD

**Issue by doggukan** [DanWin/hosting#105]
you moved the composer install at the top of the install binaries script.but since we dont have php installed ,script is failing.removed those and ran the install binary script then installed composer.no issues now

the error was env php not found

**Comment by infoabcd** [comment]
Please comment out this line in the script and execute it manually when the script is finished

`# install composer
curl -sSL https://github.com/composer/composer/releases/download/2.0.8/composer.phar > /usr/bin/composer
chmod +x /usr/bin/composer
composer self-update`

**Comment by DanWin** [comment]
Fixed in 3b7166148b1cf69ace5e1067e6d250487e64597e
