### ISSUE TITLE
composer install not working

### ISSUE THREAD

**Issue by maki64** [DanWin/hosting#110]
cd /var/www && composer install

its not working for some odd reason

**Comment by maki64** [comment]
i get this` /usr/bin/php: error while loading shared libraries: libMagickWand-7.Q16HDRI.so.8: cannot open shared object file: No such file or directory`

**Comment by DanWin** [comment]
Most likely you didn't run the install script, but executed the commands manually as you indicated in other issues. You will have to run ldconfig in order to refresh the libraries cache. Also make sure the installation directory is in your /etc/ld.so.conf

**Comment by DanWin** [comment]
Closing this as no further details were provided
