### ISSUE TITLE
Tor's problems

### ISSUE THREAD

**Issue by infoabcd** [DanWin/hosting#112]
Hello

I recently found that my onion domain will jump to https by itself, but I have not made any nginx configuration, I found that if I restart Tor， he will be available again, the problem seems to happen randomly

If restarted again, other domains may automatically jump to https, or they may be normal

**Comment by DanWin** [comment]
The automatic jumping to https is not related to the web server configuration. It is the browser trying the different variations of reaching a site when it is not reachable. Tor is unstable by nature. Sometimes these issues resolve themselves after a couple of minutes, sometimes only a restart helps.To minimize downtimes you can run multiple tor instances with the same onion services and use a tool like onion balance, which will manage them for you.
