### ISSUE TITLE
nginx error

### ISSUE THREAD

**Issue by infoabcd** [DanWin/hosting#117]
nginx: [emerg] could not build map_hash, you should increase map_hash_bucket_size: 32

**Comment by DanWin** [comment]
It looks like the default setting depends on your precessors cache line size: https://nginx.org/en/docs/http/ngx_http_map_module.html#map_hash_bucket_size
Try adding `map_hash_bucket_size 64;` inside the `http` block of your `nginx.conf`

**Comment by DanWin** [comment]
With my configuration I could go as low as `map_hash_bucket_size 1;` and it still works. So I'm closing this issue as you are most likely using a highly customized configuration with more/different maps.
