### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by NagatoYuki4** [DanWin/hosting#118]
i ran into a problem while running ./install_binaries.sh 

[ 30%] Built target aom_dsp_common
[ 30%] Built target aom_dsp_encoder
make: *** [Makefile:130: all] Error 2

it stopped at 30% please fix this thanks

**Comment by NagatoYuki4** [comment]
weird thing is this worked on rpi/OS now it does not work...

**Comment by F1nx** [comment]
Could be updates with other software related to PHP

**Comment by DanWin** [comment]
This is most likely related to always using the latest development version of all dependencies, which can sometimes break. I'll switch the scripts to using a fixed version that is known to be working
