### ISSUE TITLE
dnsmasq and bind9 Conflicts arise

### ISSUE THREAD

**Issue by infoabcd** [DanWin/hosting#120]
When doing install_binaries.sh
If dnsmasq is installed first, the installation stops when bind9 is installed

Both will not start because one is occupying port 53 and the other is not

**Comment by DanWin** [comment]
This should now be fixed, as we no longer use dnsmasq as proxy. It was previously used for forwarding .onion to tor and anything else to bind9. You can uninstall dnsmasq and copy the latest bind9 config to get rid of dnsmasq.
