### ISSUE TITLE
pathspec 'PHP-8.1.5' did not match any files known to git

### ISSUE THREAD

**Issue by aklmtst** [DanWin/hosting#123]
kali linux rolling 2022
![Screenshot_2022-04-16_12_57_26](https://user-images.githubusercontent.com/25817740/163684768-b0f0ec86-9557-4edb-97fa-af06cd7320bf.png)

**Comment by aklmtst** [comment]
moving to debian 11 and this error appears
![image](https://user-images.githubusercontent.com/25817740/163701349-6b9c78ce-1aa7-4bd4-8c6b-4e3901689152.png)

so I changed ldconfig to /sbin/ldconfig

**Comment by DanWin** [comment]
Fixed by cd9efbc4011432f9b65f7f5c05c2a97563de2b2d
