### ISSUE TITLE
ldconfig not found

### ISSUE THREAD

**Issue by aklmtst** [DanWin/hosting#124]
standard debian 11
![image](https://user-images.githubusercontent.com/25817740/163701424-882168fa-17fa-47d9-98e8-e390549ba61d.png)

just in case someone has this error, change ldconfig to /sbin/ldconfig

**Comment by sergrych** [comment]
before installation:
export PATH=$PATH:/usr/sbin
or
sh -c 'echo "export PATH=$PATH:/usr/sbin" >> ~/.bashrc'

**Comment by DanWin** [comment]
Most likely you were missing `/sbin` in your `PATH` environment variable. I've added it now to the script, so that it should be correct, see d49b2b32ad33dc6c27cbca474b3c3ffe651987be
