### ISSUE TITLE
cc1: warning: command-line option ‘-Wextra-semi’ is valid for C++/ObjC++ but not for C

### ISSUE THREAD

**Issue by sergrych** [DanWin/hosting#127]
too many type errors:
cc1: warning: command-line option ‘-Wextra-semi’ is valid for C++/ObjC++ but not for C
^Cmake[2]: *** [CMakeFiles/aom_dsp_common_avx2_intrinsics.dir/build.make:82: CMakeFiles/aom_dsp_common_avx2_intrinsics.dir/aom_dsp/x86/aom_convolve_copy_avx2.c.o] Interrupt
make[2]: *** [CMakeFiles/aom_dsp_common_sse2_intrinsics.dir/build.make:82: CMakeFiles/aom_dsp_common_sse2_intrinsics.dir/aom_dsp/x86/aom_convolve_copy_sse2.c.o] Interrupt

How to fix it?
ps: 
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

**Comment by DanWin** [comment]
This is reated to aom, which is no longer built from source.
