### ISSUE TITLE
registration takes too long

### ISSUE THREAD

**Issue by zwieblinger** [DanWin/hosting#131]
The installation of the script runs without problems until the end.
When I register a user, the URL is listed and it seems the registration is complete, but the login does not work.

**Comment by DanWin** [comment]
Hello @zwieblinger , sounds like you didn't complete the final steps of enabling systemd timers and rebooting. Account creation should run every minute.

**Comment by DanWin** [comment]
Hmm, I see. If your VM doesn't survive a reboot, then something is broken. Do you still have access to the terminal or ssh? If so, I'd suggest to run `journalctl` and look through the logs. Maybe there is an error message that could help you identify the issue.

**Comment by DanWin** [comment]
Yes, tor can take a few minutes sometimes. Especially if you've been previously connected, it's often good to change identity, or restart the tor client, when trying to connect to the hidden service again after a reboot.
Try removing the `sntrup761x25519-sha512@openssh.com` from `KexAlgorithms` in `/etc/ssh/sshd_config` it is only supported in most recent ssh versions. Perhaps your OS is shipping an outdated version of ssh, where it is not yet supported.
As for database connection, you should check the mariadb.service with `journalctl -u mariadb.service` or take a look at `/var/log/mysql/error.log`, depending on where it is logged to.
