### ISSUE TITLE
Issue with Installation Script on Debian VPS via SSH (Termux)

### ISSUE THREAD

**Issue by MHackerkhan** [DanWin/hosting#139]
I am encountering an issue while attempting to run the installation script (`install_binaries.sh`) on my Debian VPS, accessed through an SSH connection using Termux on my Android device.

Specifically, the process is failing due to the inability to locate the package `libnginx-mod-http-brotli`.

Here are the details of my setup:

- VPS: Debian
- Connection: SSH via Termux (Android)
- Script: `install_binaries.sh`

I have tried updating the package index and checking package availability, but the issue persists.

Would you kindly provide guidance or assistance in resolving this matter?

Thank you for your time and support.

Regards,

mbkmadmax

**Comment by DanWin** [comment]
Hello @MHackerkhan , it sounds like you skipped one of the first steps ´Add additional repositories:´
```
apt update && apt install git apt-transport-tor curl
curl -sSL https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc > /etc/apt/trusted.gpg.d/torproject.gpg
curl -sSL https://packages.sury.org/nginx/apt.gpg > /etc/apt/trusted.gpg.d/sury.gpg
echo "deb tor://apow7mjfryruh65chtdydfmqfpj5btws7nbocgtaovhvezgccyjazpqd.onion/torproject.org/ `lsb_release -cs` main" >> /etc/apt/sources.list
echo "deb https://packages.sury.org/nginx/ `lsb_release -cs` main" >> /etc/apt/sources.list
apt update && apt upgrade
```
The package is not (yet) available on default debian repositories. If you prefer to stick to default debian only, you can remove this package from the install script and remove brotli related configuration from nginx.
Brotli is not required, but a more efficient compression algorithm than gzip, which will be available also without the extra repository.

**Comment by MHackerkhan** [comment]
Thanks
