### ISSUE TITLE
Issue with installation of ./install_binaries.sh

### ISSUE THREAD

**Issue by MHackerkhan** [DanWin/hosting#140]
Now Another issue Faced
The installation Just Stoped at this point

Creating config file /etc/dovecot/conf.d/auth-system.conf.ext with new version
Created symlink /etc/systemd/system/multi-user.target.wants/dovecot.service → /lib/systemd/system/dovecot.service.
dovecot.socket is a disabled or a static unit, not starting it.
Setting up rspamd (3.4-1) ...
Reload daemon failed: Connection timed out

file: ./install_binaries.sh
issue: did not responding or stoped moving forward

**Comment by DEAM0** [comment]
what system you use?

**Comment by MHackerkhan** [comment]
It Debain 12 vps
And i get vps from Aws Amazon Ec2 Free tier

**Comment by MHackerkhan** [comment]
I'm just an IT and Computer Science student, but I have a strong desire to achieve my goals. Honestly, I only have basic knowledge, so I don't know why just copy-paste commands give me a lot of unwanted errors.
But I won't give up! I'm only 20, and I'm eager to learn.

**Comment by DEAM0** [comment]
you can copy full log here?

**Comment by MHackerkhan** [comment]
Sure give me a minute because i just terminate the vps i well copy it here in some minutes

**Comment by DEAM0** [comment]
okey bro

**Comment by MHackerkhan** [comment]
Can i have you telegram or any direct contact i am in learning stage so i need expert to ask

**Comment by DEAM0** [comment]
yes i have

**Comment by MHackerkhan** [comment]
Username please

**Comment by MHackerkhan** [comment]
See you there on telegram ok well further disscuss the issue and find solution so we well paste it here

**Comment by DEAM0** [comment]
okey

**Comment by MHackerkhan** [comment]
*Error Resolution Summary*

*Issue:* Script execution failure
*Cause:* Insufficient system resources (low CPU and limited resources)
*Resolution:* System specifications upgrade or optimization required
*Script Status:* Script is fine, no modifications needed

*Key Takeaways:*

1. System resource limitations caused script execution failure.
2. Low CPU and limited resources hindered script performance.
3. Script itself is error-free and functional.
4. Upgrading system specifications or optimizing resource usage necessary to resolve issue.
