### ISSUE TITLE
Code hardening ideas

### ISSUE THREAD

**Issue by jtesta** [DanWin/hosting#29]
I browsed the source code a little bit, and came up with some hardening ideas (note that I didn't do an exhaustive review... just notes on some things that stood out to me).
In /var/www/cron.php:

- The password hash is leaked in the process listing to anyone doing a "ps" at the right moment, since the "-p" option is used with `useradd` and `usermod`.  See lines 29 and 242.
- Because the `$system_account` variable (line 24) is used to build a filesystem path in multiple places, it should first be filtered through the `basename()` call.  This will prevent relative path attacks, which could cause a root compromise if an attacker has control of it.
- `$system_account` should be validated through `posix_getpwnam()` before performing any actions on existing accounts.
- Perhaps `$system_account` can also be checked against a short blacklist of disallowed account names, such as `root`, `daemon`, `bin`, etc.  In some cases, it may make sense to resolve to a UID & GID and check that neither is under 1000.

I see possibilities where, if an attacker has access to insert unfiltered data into the database, `cron.php` can be used to elevate privileges to root.

Considering that you had a full system compromise, I'd spend a lot of time looking at the code executing with root privileges.

**Comment by DanWin** [comment]
Thanks for the suggestions. 93dc5b10c472fe4c9caf1f83055c774458b5500c and 47fb98355778d0ddfd176a6d9ea7cc7f5ee50a59 implement the necessary changes
