### ISSUE TITLE
.ssh ownership

### ISSUE THREAD

**Issue by setharnold** [DanWin/hosting#30]
https://github.com/DanWin/hosting/blob/db626a54a4f5e3ed4673b88834d6fda3e63f5152/var/www/cron.php#L33

I don't understand why `www-data` should have extra privileges on `.ssh`.

Thanks

**Comment by setharnold** [comment]
On Wed, Nov 21, 2018, 21:28 Daniel Winzen <notifications@github.com wrote:

> www-data actually doesn't have any permissions on .ssh, only the
> $system_account user. This is done to let the user upload eg. an
> authorized_keys file and connect with an ssh key instead of having to use
> a password every time.
>

Are you sure? I'm pretty sure I remember seeing it also setting the mode to
0550.

Thanks

>

**Comment by DanWin** [comment]
https://github.com/DanWin/hosting/blob/db626a54a4f5e3ed4673b88834d6fda3e63f5152/var/www/cron.php#L34
The mode for the `.ssh` is set to 0700 when creating the directory one line below.

**Comment by setharnold** [comment]
Sigh. Thanks. Sorry. :)

**Comment by DanWin** [comment]
As ownership is correctly set, I'm closing this issue
