### ISSUE TITLE
race condition

### ISSUE THREAD

**Issue by setharnold** [DanWin/hosting#31]
https://github.com/DanWin/hosting/blob/db626a54a4f5e3ed4673b88834d6fda3e63f5152/var/www/cron.php#L120

Hello, this appears to be a race condition on a single file with well-known name, multiple processes going through this section of code at once might stomp on each other. See `mkstemp(3)` for one correct way to make temporary files.

Thanks

**Comment by DanWin** [comment]
Thanks, with multiple processes running it could be a race condition and should be fixed. However that should practically never happen as the scheduler is waiting for the old process to exit before re-starting.

**Comment by DanWin** [comment]
Fixed in 756e16b
