### ISSUE TITLE
possible sql injection site

### ISSUE THREAD

**Issue by setharnold** [DanWin/hosting#32]
https://github.com/DanWin/hosting/blob/db626a54a4f5e3ed4673b88834d6fda3e63f5152/var/www/cron.php#L228

This SQL isn't using prepared statements with placeholders; unless the input variable is properly sanitized elsewhere in the codebase this may represent an SQL injection opportunity.

Thanks

**Comment by DanWin** [comment]
Thanks for pointing it out, this is now resolved.
