### ISSUE TITLE
PHP is out, you should use Rust

### ISSUE THREAD

**Issue by VitalyAnkh** [DanWin/hosting#33]
As the title.

**Comment by bet0x** [comment]
https://avadacatavra.github.io/attackingrustforfunandprofit/  And you can goole many more. Do not blame PHP.

**Comment by ForsakenHarmony** [comment]
200iq comment that got deleted, tried to bash rust with an article where the conclusion was that it's a good lang 👌

**Comment by DanWin** [comment]
For reference, the deleted comment linked to this article: https://avadacatavra.github.io/attackingrustforfunandprofit/
