### ISSUE TITLE
Composer + writable home directory

### ISSUE THREAD

**Issue by DanWin** [DanWin/hosting#48]
But it Will be good if you enable and create a home directory for each user. This is because it is currently impossible to install Composer without configuring it to use different dir.  It is also the same for other programs that require a home dir for saving the configuration. If /home/USER would be enabled, it probably won't have any security issues.

Also, maybe you can also pre-install Composer because it is used in many projects.

**Comment by filips123** [comment]
I can help you with that, but first I need to figure out how does your system work.

---

If I correctly understand your code, user is added [with this code](https://github.com/DanWin/hosting/blob/master/var/www/cron.php#L22-L45), which then calls [setup chroot](https://github.com/DanWin/hosting/blob/master/var/www/setup_chroot.sh). In this file, user's directory structure is created.

So home directory should be created there and Composer should also be installed in it.

Also, `/etc/profile` then needs to be updated to use `$HOME/.composer/vendor/bin/` in PATH (for Composer global packages).

Also, it should also be updated to use `.bashrc` or `.profile` in user's home directory. This would enable easier costumisation of shell. Which of them should be sued?

---

Is this correct? If it is, I can submit pull request.

Also, what is point of `test -d` and `diff` commands in  [setup chroot](https://github.com/DanWin/hosting/blob/master/var/www/setup_chroot.sh)? Are they to prevent overwriting existing files and directories in target

**Comment by DanWin** [comment]
Composer is installed since 4096b663905096ec1e0e21f97a02fa00867b21cc and there are new empty files and dirs for configuration/cache available since 264eacc and Composer global packages are included in the PATH since b2da71f
The test/diff commands were useful to prevent copying the same file multiple times when referenced by another. However, I have removed those in ae925a2000e2ef0632d3845981973dada0eba94e as simplification
