### ISSUE TITLE
first demo with the new frontent

### ISSUE THREAD

**Issue by 01123581321345589144233** [DanWin/hosting#61]
first demo with the new frontent, the main site will also where in the same design
http://yzombq2l4b6mnyw2icm23faq34nv2fjjfpm44v6thg43gsiefc3qfwid.onion

**Comment by linhux** [comment]
the backend comes later :-)

**Comment by NoahvdAa** [comment]
I don't like how your site has Google Analytics and AddToAny.

**Comment by linhux** [comment]
there is no google analytics, i have added only css

**Comment by NoahvdAa** [comment]
> there is no google analytics, i have added only css

Woops, my bad, I was in a bit of a hurry so I probably confused two things with one another.
I like the design, but I feel like the buttons at the top are way too big.

**Comment by linhux** [comment]
Ah ok :-), yes i change the navigation on the top to a topbar menu.

**Comment by linhux** [comment]
its changed :-)

**Comment by NoahvdAa** [comment]
The **List of hosted sites** page looks a bit weird with a random dot (left) and a weird hover effect.

**Comment by linhux** [comment]
yes this was only a test :-), the onion domains are also responsive now

**Comment by linhux** [comment]
i have added a nes section https://github.com/linhux/hosting
so the admin can send news to the mainsite, there can only add news from the admin section

**Comment by MuzahidApps** [comment]
😂 
You worked like a kid bro. 
Don't do this. Pro Designs Coming soon with fully customized & secured in house JavaScript & CSS frameworks.

**Comment by linhux** [comment]
You dont understand tor ! Daniels site is working without javascript. So its so simple.

**Comment by MuzahidGithub** [comment]
This site is being designed while keeping JavaScript Dependability & Tor in mind. It will look & work same with or without JavaScript. JavaScript will give some extra smoothness. This scripts I m using is modified(Extra Unneeded codes removed, any tracking & 3rd party includes have removed )  
Soon I will offer a Tor CDN for my users to use this on their sites. 
Soon I will apply this on my site.
Chill Buddy 😎
Thanks For Your Understanding.

**Comment by NoahvdAa** [comment]
> You dont understand tor ! Daniels site is working without javascript. So its so simple.
> When you use the torbrowser in hightest secure mode is javascript deaktivatet, and a site with javascript will not work.
> Also as default when you surf in the tornetwork you should deaktivate javascript

I'd like to also add that TOR can be slow sometimes so pages with heavy css like @MuzahidGithub 's can take ages to load properly

**Comment by MuzahidGithub** [comment]
New frontend is live ( few non important pages not updated yet ) 
I have tested and its loading very fast.(still in testing )
Please check is their any problem in the design that need to be fixed. 
https://onionmax.com/
