### ISSUE TITLE
Step by step Detailed tut

### ISSUE THREAD

**Issue by whokid** [DanWin/hosting#65]
Is there any detailed tut for this setup I cant get this working at all someone please help me

**Comment by whokid** [comment]
I have got it up and ranning now i will make a more detailed tut for this i love this project and took me a week to work it out without any help from anyone how sad is that but I will soon post a step by step on how to install it there many things the readme have left out or not in order eg install the webserver first to avoid errors 

install aptitude install libssl-dev so Custom optimized nginx works right

apt-get --no-install-recommends install libbrotli-dev libpcre3-dev zlib1g-dev
git clone https://github.com/nginx/nginx && cd nginx
git clone https://github.com/eustas/ngx_brotli
./auto/configure --prefix=/usr/share/nginx --sbin-path=/usr/sbin --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/tmp/body --http-fastcgi-temp-path=/tmp/fastcgi --http-proxy-temp-path=/tmp/proxy --with-threads --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-http_gzip_static_module --without-http_ssi_module --without-http_userid_module --without-http_access_module --without-http_mirror_module --without-http_geo_module --without-http_split_clients_module --without-http_uwsgi_module --without-http_scgi_module --without-http_grpc_module --without-http_memcached_module --without-http_limit_conn_module --without-http_limit_req_module --without-http_empty_gif_module --without-http_browser_module --without-http_upstream_hash_module --without-http_upstream_ip_hash_module --without-http_upstream_least_conn_module --without-http_upstream_keepalive_module --without-http_upstream_zone_module --with-stream --with-stream_ssl_module --without-stream_limit_conn_module --without-stream_access_module --without-stream_geo_module --without-stream_map_module --without-stream_split_clients_module --without-stream_return_module --without-stream_upstream_hash_module --without-stream_upstream_least_conn_module --without-stream_upstream_zone_module --with-cc-opt='-O3 -march=native -mtune=native -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -fPIC' --add-module=ngx_brotli
make -j $(nproc) install

**Comment by linhux** [comment]
have zou try with debian 10 ? what is the issue ?

**Comment by DanWin** [comment]
The Readme has detailed step-by-step instructions by now, but I also just released a video tutorial on youtube, which may make it easier to consume in a non-textual way: https://www.youtube.com/watch?v=f2-SOlnIYmg
