### ISSUE TITLE
install_binaries 

### ISSUE THREAD

**Issue by linhux** [DanWin/hosting#69]
error: fehlerhafter Patch bei Zeile 263
./auto/configure: error: invalid option "--with-http_v2_hpack_enc"

**Comment by linhux** [comment]
Daniel, what are you use for a nginx version ?

**Comment by linhux** [comment]
i have setup a new system but still the same issue

**Comment by DanWin** [comment]
The `\` at line ending within heredoc needed escaping. Fixed in b09aa25d8888b7e30275510fc2fb2f322b6c177f
