### ISSUE TITLE
Ungültiger Anwender „_tor-a“

### ISSUE THREAD

**Issue by linhux** [DanWin/hosting#70]
I have setup your system, and i try to create a new hidden service but the onion domain was not found. And i found out the process are not starting.
Thats my link http://ommmmmmiq65cbweoseups4pndieajosfgk7jzwraotrn6sxhqy6ik6qd.onion

### Dec 25 19:24:09 #### systemd[1]: Starting Anonymizing overlay network for TCP (instance a)...
-- Subject: A start job for unit tor@a.service has begun execution
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit tor@a.service has begun execution.
-- 
-- The job identifier is 16467.
Dec 25 19:24:09 #### install[15913]: /usr/bin/install: Ungültiger Anwender „_tor-a“
Dec 25 19:24:09 #### systemd[1]: tor@a.service: Control process exited, code=exited, status=1/FAILURE
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStartPre= process belonging to unit tor@a.service has exited.
-- 
-- The process' exit code is 'exited' and its exit status is 1.
Dec 25 19:24:09 gugu1 systemd[1]: tor@a.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit tor@a.service has entered the 'failed' state with result 'exit-code'.
Dec 25 19:24:09 gugu1 systemd[1]: Failed to start Anonymizing overlay network for TCP (instance a).
-- Subject: A start job for unit tor@a.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit tor@a.service has finished with a failure.
-- 
-- The job identifier is 16467 and the job result is failed.

_**

**Comment by linhux** [comment]
I have changed my config to only 3 instances, so and when i reboot or start the processes manuel there is this:
/var/www# systemctl status tor@a.service
● tor@a.service - Anonymizing overlay network for TCP (instance a)
     Loaded: loaded (/lib/systemd/system/tor@.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sat 2019-12-28 13:54:32 CET; 4s ago
    Process: 25667 ExecStartPre=/usr/bin/install -Z -m 02755 -o _tor-a -g _tor-a -d /run/tor-instances/a (code=exited, status=1/FAILURE)

Dec 28 13:54:32 #### systemd[1]: tor@a.service: Scheduled restart job, restart counter is at 5.
Dec 28 13:54:32 #### systemd[1]: Stopped Anonymizing overlay network for TCP (instance a).
Dec 28 13:54:32 #### systemd[1]: tor@a.service: Start request repeated too quickly.
Dec 28 13:54:32 #### systemd[1]: tor@a.service: Failed with result 'exit-code'.
Dec 28 13:54:32 #### systemd[1]: Failed to start Anonymizing overlay network for TCP (instance a).

**Comment by linhux** [comment]
ok i found the issue, the tor instance users are not createt.
Change line 298 from
exec('useradd -d '.escapeshellarg("/var/lib/tor-instances/$instance").' -r -s /bin/false -M -U '.escapeshellarg("_tor-$instance"));
to
exec('/sbin/useradd -d '.escapeshellarg("/var/lib/tor-instances/$instance").' -r -s /bin/false -M -U '.escapeshellarg("_tor-$instance"));
and line 324
exec('userdel '.escapeshellarg("_tor-$tmp[0]"));
to
exec('/sbin/userdel '.escapeshellarg("_tor-$tmp[0]"));

My setup is a default debian 10 and now i works.

**Comment by DanWin** [comment]
Looks like `/sbin` is missing in your `$PATH`. Were you perhaps not using the root account, but a less privileged account and using `sudo` or `su` when setting it up? As each distro places binaries in different locations, it's best not to hardcode these values and leave it to the shell to find the executable.

**Comment by linhux** [comment]
thanks, yes its resolved

**Comment by linhux** [comment]
thanks, ist resolved
