### ISSUE TITLE
Issue with generating tor address

### ISSUE THREAD

**Issue by RobCod** [DanWin/hosting#83]
When I use the provided /etc files there is no tor address generated in /var/lib/tor after restarting the service when I am trying to set it up

**Comment by DanWin** [comment]
When you issue the following command, it should tell you what's the issue. Can you share the log output of this?
`systemctl restart tor@default.service && journalctl -fu tor@default.service`

**Comment by RobCod** [comment]
It runs perfectly fine with no errors, but there is no file generated

**Comment by DanWin** [comment]
This looks like the output of `systemctl status tor@default.service` which however only shows the last few lines and cuts them at the end of your terminal line. The actual error message is hidden a little further up in history. Can you post the content of this please?
`journalctl -u tor@default.service | cat`

**Comment by RobCod** [comment]
-- Logs begin at Tue 2020-04-07 20:17:01 BST, end at Tue 2020-04-07 20:56:36 BST. --
Apr 07 20:56:05 raspberrypi systemd[1]: Starting Anonymizing overlay network for TCP...
Apr 07 20:56:06 raspberrypi tor[797]: Apr 07 20:56:06.193 [notice] Tor 0.3.5.10 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
Apr 07 20:56:06 raspberrypi tor[797]: Apr 07 20:56:06.193 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Apr 07 20:56:06 raspberrypi tor[797]: Apr 07 20:56:06.221 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
Apr 07 20:56:06 raspberrypi tor[797]: Apr 07 20:56:06.277 [notice] Read configuration file "/etc/tor/torrc".
Apr 07 20:56:06 raspberrypi tor[797]: Apr 07 20:56:06.404 [warn] Failed to parse/validate config: Unknown option 'HiddenServiceEnableIntroDoSDefense'.  Failing.
Apr 07 20:56:06 raspberrypi tor[797]: Apr 07 20:56:06.404 [err] Reading config failed--see warnings above.
Apr 07 20:56:06 raspberrypi systemd[1]: tor@default.service: Control process exited, code=exited, status=1/FAILURE
Apr 07 20:56:06 raspberrypi systemd[1]: tor@default.service: Failed with result 'exit-code'.
Apr 07 20:56:06 raspberrypi systemd[1]: Failed to start Anonymizing overlay network for TCP.
Apr 07 20:56:06 raspberrypi systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Apr 07 20:56:06 raspberrypi systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 1.
Apr 07 20:56:06 raspberrypi systemd[1]: Stopped Anonymizing overlay network for TCP.
Apr 07 20:56:06 raspberrypi systemd[1]: Starting Anonymizing overlay network for TCP...
Apr 07 20:56:06 raspberrypi tor[842]: Apr 07 20:56:06.955 [notice] Tor 0.3.5.10 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
Apr 07 20:56:06 raspberrypi tor[842]: Apr 07 20:56:06.955 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Apr 07 20:56:06 raspberrypi tor[842]: Apr 07 20:56:06.956 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
Apr 07 20:56:06 raspberrypi tor[842]: Apr 07 20:56:06.956 [notice] Read configuration file "/etc/tor/torrc".
Apr 07 20:56:06 raspberrypi tor[842]: Apr 07 20:56:06.977 [warn] Failed to parse/validate config: Unknown option 'HiddenServiceEnableIntroDoSDefense'.  Failing.
Apr 07 20:56:06 raspberrypi tor[842]: Apr 07 20:56:06.977 [err] Reading config failed--see warnings above.
Apr 07 20:56:07 raspberrypi systemd[1]: tor@default.service: Control process exited, code=exited, status=1/FAILURE
Apr 07 20:56:07 raspberrypi systemd[1]: tor@default.service: Failed with result 'exit-code'.
Apr 07 20:56:07 raspberrypi systemd[1]: Failed to start Anonymizing overlay network for TCP.
Apr 07 20:56:07 raspberrypi systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Apr 07 20:56:07 raspberrypi systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 2.
Apr 07 20:56:07 raspberrypi systemd[1]: Stopped Anonymizing overlay network for TCP.
Apr 07 20:56:07 raspberrypi systemd[1]: Starting Anonymizing overlay network for TCP...
Apr 07 20:56:07 raspberrypi tor[889]: Apr 07 20:56:07.449 [notice] Tor 0.3.5.10 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
Apr 07 20:56:07 raspberrypi tor[889]: Apr 07 20:56:07.450 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Apr 07 20:56:07 raspberrypi tor[889]: Apr 07 20:56:07.450 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
Apr 07 20:56:07 raspberrypi tor[889]: Apr 07 20:56:07.450 [notice] Read configuration file "/etc/tor/torrc".
Apr 07 20:56:07 raspberrypi tor[889]: Apr 07 20:56:07.471 [warn] Failed to parse/validate config: Unknown option 'HiddenServiceEnableIntroDoSDefense'.  Failing.
Apr 07 20:56:07 raspberrypi tor[889]: Apr 07 20:56:07.471 [err] Reading config failed--see warnings above.
Apr 07 20:56:07 raspberrypi systemd[1]: tor@default.service: Control process exited, code=exited, status=1/FAILURE
Apr 07 20:56:07 raspberrypi systemd[1]: tor@default.service: Failed with result 'exit-code'.
Apr 07 20:56:07 raspberrypi systemd[1]: Failed to start Anonymizing overlay network for TCP.
Apr 07 20:56:07 raspberrypi systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Apr 07 20:56:07 raspberrypi systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 3.
Apr 07 20:56:07 raspberrypi systemd[1]: Stopped Anonymizing overlay network for TCP.
Apr 07 20:56:07 raspberrypi systemd[1]: Starting Anonymizing overlay network for TCP...
Apr 07 20:56:07 raspberrypi tor[919]: Apr 07 20:56:07.955 [notice] Tor 0.3.5.10 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
Apr 07 20:56:07 raspberrypi tor[919]: Apr 07 20:56:07.955 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Apr 07 20:56:07 raspberrypi tor[919]: Apr 07 20:56:07.955 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
Apr 07 20:56:07 raspberrypi tor[919]: Apr 07 20:56:07.956 [notice] Read configuration file "/etc/tor/torrc".
Apr 07 20:56:07 raspberrypi tor[919]: Apr 07 20:56:07.976 [warn] Failed to parse/validate config: Unknown option 'HiddenServiceEnableIntroDoSDefense'.  Failing.
Apr 07 20:56:07 raspberrypi tor[919]: Apr 07 20:56:07.976 [err] Reading config failed--see warnings above.
Apr 07 20:56:08 raspberrypi systemd[1]: tor@default.service: Control process exited, code=exited, status=1/FAILURE
Apr 07 20:56:08 raspberrypi systemd[1]: tor@default.service: Failed with result 'exit-code'.
Apr 07 20:56:08 raspberrypi systemd[1]: Failed to start Anonymizing overlay network for TCP.
Apr 07 20:56:08 raspberrypi systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Apr 07 20:56:08 raspberrypi systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 4.
Apr 07 20:56:08 raspberrypi systemd[1]: Stopped Anonymizing overlay network for TCP.
Apr 07 20:56:08 raspberrypi systemd[1]: Starting Anonymizing overlay network for TCP...
Apr 07 20:56:08 raspberrypi tor[934]: Apr 07 20:56:08.470 [notice] Tor 0.3.5.10 running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.1d, Zlib 1.2.11, Liblzma 5.2.4, and Libzstd 1.3.8.
Apr 07 20:56:08 raspberrypi tor[934]: Apr 07 20:56:08.474 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Apr 07 20:56:08 raspberrypi tor[934]: Apr 07 20:56:08.475 [notice] Read configuration file "/usr/share/tor/tor-service-defaults-torrc".
Apr 07 20:56:08 raspberrypi tor[934]: Apr 07 20:56:08.476 [notice] Read configuration file "/etc/tor/torrc".
Apr 07 20:56:08 raspberrypi tor[934]: Apr 07 20:56:08.499 [warn] Failed to parse/validate config: Unknown option 'HiddenServiceEnableIntroDoSDefense'.  Failing.
Apr 07 20:56:08 raspberrypi tor[934]: Apr 07 20:56:08.500 [err] Reading config failed--see warnings above.
Apr 07 20:56:08 raspberrypi systemd[1]: tor@default.service: Control process exited, code=exited, status=1/FAILURE
Apr 07 20:56:08 raspberrypi systemd[1]: tor@default.service: Failed with result 'exit-code'.
Apr 07 20:56:08 raspberrypi systemd[1]: Failed to start Anonymizing overlay network for TCP.
Apr 07 20:56:08 raspberrypi systemd[1]: tor@default.service: Service RestartSec=100ms expired, scheduling restart.
Apr 07 20:56:08 raspberrypi systemd[1]: tor@default.service: Scheduled restart job, restart counter is at 5.
Apr 07 20:56:08 raspberrypi systemd[1]: Stopped Anonymizing overlay network for TCP.
Apr 07 20:56:08 raspberrypi systemd[1]: tor@default.service: Start request repeated too quickly.
Apr 07 20:56:08 raspberrypi systemd[1]: tor@default.service: Failed with result 'exit-code'.
Apr 07 20:56:08 raspberrypi systemd[1]: Failed to start Anonymizing overlay network for TCP.

**Comment by DanWin** [comment]
This is the error you are facing: `[warn] Failed to parse/validate config: Unknown option 'HiddenServiceEnableIntroDoSDefense'.  Failing.`
You are using `Tor 0.3.2.10 (git-0edaa32732ec8930)`, which is outdated. The current version of Tor is `0.4.2.7`. I would strongly recommend you update to the latest version of tor by adding the torproject repository to your `/etc/apt/sources.list` config file (one of the first steps in the install instructions) and then run `apt-get update && apt-get upgrade` and maybe add a `apt-get dist-upgrade` if there are packages not being updated.
Alternatively you could just remove the DoSDefense related options.

**Comment by RobCod** [comment]
hmm alright, I thought I did update tor, maybe I forgot to run the update, thanks I'll report back if it works

**Comment by RobCod** [comment]
Just for the future for the new tor you need several dependencies that Ubuntu 18.04 doesn't have, for example libc6 2.29 which ubuntu 19.04 has

**Comment by DanWin** [comment]
Looks like you were mixing different distributions. You were trying to install a Tor version that was compiled for Ubuntu 19.10 (or maybe Debian unstable as per the example in my readme?) on a Ubuntu 18.04. Always make sure your distribution code in the repositories you add are correct, to avoid dependency problems.
Because you are not the first one who copy-pasted the instructions, without changing the distribution code to the one you are using, I've just added auto-detection of the correct code to use in 588082e6d048a9f6ff8d4e874cf2b21a59ca9da3

**Comment by RobCod** [comment]
thanks lol
