### ISSUE TITLE
install_binaries.sh error.

### ISSUE THREAD

**Issue by CoderTheNaked** [DanWin/hosting#85]
OS: Debian 10.4

error: patch failed: src/event/ngx_event_openssl.h:64
error: src/event/ngx_event_openssl.h: patch does not apply
error: patch failed: src/http/modules/ngx_http_ssl_module.c:580
error: src/http/modules/ngx_http_ssl_module.c: patch does not apply
./auto/configure: error: invalid option "--with-http_v2_hpack_enc"
make: *** No rule to make target 'install'.  Stop.
make: *** No rule to make target 'clean'.  Stop.
HEAD is now at 59a0ceb9 Contrib: vim syntax, update core and 3rd party module directives.

**Comment by DanWin** [comment]
Fixed in 4e183a490edc1dc91b6dc431cfc59b71ccfea3cc
