### ISSUE TITLE
/etc/fstab There is no /home part

### ISSUE THREAD

**Issue by CoderTheNaked** [DanWin/hosting#86]
Hello.  (This is not issue)

I tried script, it worked well without no /home part at /etc/fstab 

Can i add it manually? And what it is for?

And i want to work this script without ROOT, is it possible? will copy-paste process work with adding sudo before the commands?

Thanks your helps and efforts.

**Comment by DanWin** [comment]
The `/home` part refers to the file system that has `/home` in it. Usually that is either its own partition, or it is part of the `/` mountpoint.
You need to be root for most operations, as you require write privileges to system folders. Using the `sudo` program effectively makes you root for the time of running a given command. So yes, it's possible to setup as a non-root user, but run everything with `sudo`. Much easier would however be running `sudo -i` once and stay sudo for the entire setup session.
