### ISSUE TITLE
Nginx cannot start

### ISSUE THREAD

**Issue by TangLiChun** [DanWin/hosting#88]
Jul 12 04:28:56 debian systemd[1]: Starting A high performance web server and a reverse proxy server...
Jul 12 04:28:56 debian systemd[31694]: nginx.service: Failed to execute command: No such file or directory
Jul 12 04:28:56 debian systemd[31694]: nginx.service: Failed at step EXEC spawning /usr/sbin/nginx: No such file or direJul 12 04:28:56 debian systemd[1]: nginx.service: Control process exited, code=exited, status=203/EXEC
Jul 12 04:28:56 debian systemd[1]: nginx.service: Failed with result 'exit-code'.
Jul 12 04:28:56 debian systemd[1]: Failed to start A high performance web server and a reverse proxy server.
~

**Comment by TangLiChun** [comment]
Doesn't seem to have been installed successfully? But I found no error during installation

**Comment by TangLiChun** [comment]
make: *** No rule to make target 'install'. Stop.

**Comment by TangLiChun** [comment]
nginx: error while loading shared libraries: libluajit-5.1.so.2: cannot open shared object file: No such file or directory

**Comment by DanWin** [comment]
run `ldconfig` to update your LD cache. Just added it to the script in 7902994

**Comment by TangLiChun** [comment]
The test was successful. Thank you
