### ISSUE TITLE
install-binaries nginx make fail

### ISSUE THREAD

**Issue by doggukan** [DanWin/hosting#89]
using the script, by accident i see the line causing isse.it was because of libatomic.even tho it is installed on the system "make" fails with error like libatomic not found.

debian 10 fresh install.cant exactly copy the error but it was libatomics-ops libs not found issue.as soon as script stops i will post here exact error just in case.

`Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
`

**Comment by doggukan** [comment]
`checking for atomic_ops library ... not found

./auto/configure: error: libatomic_ops library was not found.

`

**Comment by doggukan** [comment]
installed latomic from git.set the lib path to --with-libatomic=/usr/local/lib and manually entering codes to the console.and for some reason it worked.now conitiniues to clone php

**Comment by doggukan** [comment]
Fixed by this (dirty but works)

Download libatomic from github links.(easy to find)
Create directory under hosting/libatomic
Extract Archive to hosting/libatomic
Go inside libatomic folder and run install commands from repo
Copy all lib* files from /usr/local/lib to hosting/libatomic/src
Edit the  --with-libatomic to --with-libatomic=../libatomic
Run the script again(i manually entered commands for debugging.)

**Comment by doggukan** [comment]
everything works.but when i register account onion doesnt gets live waited around 30 minutes

**Comment by DanWin** [comment]
nginx does indeed seem to expect libatomic_ops to be shipped as source code and built from scratch 98a1eb29669ce1afd2baf461c3e686f5a32062ef should fix this issue
