### ISSUE TITLE
Nginx suddenly stopped working

### ISSUE THREAD

**Issue by TangLiChun** [DanWin/hosting#92]
In the middle of the night, Tor, MySQL, Nginx and other applications occupied a large amount of CPU, which caused the server to shut down

The following problems occur with Nginx on reboot
![IMG_20200730_042353](https://user-images.githubusercontent.com/68064465/88849482-875a9800-d21c-11ea-8ed0-6c2877f0eb12.jpg)

**Comment by DanWin** [comment]
Hello, did you modify the setup to reduce ressource usage yet? Unless you are hosting hundreds of hidden services, you can greatly reduce the mysql memory footprint, as well as reduce the number of connections Tor keeps active.
Regarding the startup issue, run the following script before restarting nginx: https://github.com/DanWin/hosting/blob/master/clean_nginx_sockets.sh

**Comment by TangLiChun** [comment]
I canceled the ClamAV Settings
