### ISSUE TITLE
An error occurred while executing setup.php

### ISSUE THREAD

**Issue by infoabcd** [DanWin/hosting#93]
`cp: cannot stat '/etc/bash_completion': No such file or directory
cp: cannot stat '/usr/share/bash-completion/bash_completion': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/alias': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/bind': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/bzip2': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/compgen': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/complete': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/curl': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/declare': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/export': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/find': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/function': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/gzip': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/id': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/kill': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/mysql': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/openssl': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/pwd': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/rsync': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/scp': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/sh': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/sftp': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/tar': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/typeset': No such file or directory
cp: cannot stat '/usr/share/bash-completion/completions/wget': No such file or directory
`
But it doesn't seem to have any effect on me

**Comment by DanWin** [comment]
It looks like you haven't installed the bash-completion package yet. It's not necessary for the chroot created by setup.php, but I would recommend installing it via `apt-get install bash-completion`, so that your users can have auto completion and suggestions, when logged in via ssh.

**Comment by kmes103266** [comment]
It worked. I used a simplified version of Debian10

**Comment by kmes103266** [comment]
Run successfully

**Comment by infoabcd** [comment]
Run successfully
