### ISSUE TITLE
install_binaries.sh Perform error

### ISSUE THREAD

**Issue by kmes103266** [DanWin/hosting#94]
The following error occurred at the end of compilation

![Screenshot_20200818_195257](https://user-images.githubusercontent.com/69637366/90510068-e3b23700-e18c-11ea-8f1f-d56767168b8d.jpg)

**Comment by kmes103266** [comment]
The following prompts appear when installing dependencies

No schema files found: doing nothing.

**Comment by DanWin** [comment]
It looks like the latest changes introduced in the ImageMagick PHP extension are no longer compatible with the legacy version 6 of ImageMagick that comes shipped with Debian/Ubuntu. 5531886289d3230847e290ac3afa3d23bc935361 replaces the version currently used with the latest version of ImageMagick and now the build works again for me.
