### ISSUE TITLE
Unable to locate software package

### ISSUE THREAD

**Issue by kmes103266** [DanWin/hosting#95]
E: Unable to locate package libfreetype-dev

**Comment by kmes103266** [comment]
It seems to be

`libfreetype6-dev`

**Comment by kmes103266** [comment]
![Screenshot_20200820_120824](https://user-images.githubusercontent.com/69637366/90715815-ecfee900-e2dd-11ea-8f12-b362bac6ed44.jpg)

**Comment by kmes103266** [comment]
`libfreetype6-dev`

**Comment by DanWin** [comment]
You are likely installing the software on one of the older distributions. As of debian `bullseye` and ubuntu `focal` the package was renamed from `libfreetype6-dev` to `libfreetype-dev`. On older distribution versions, you can safely switch back the name. Same applies to `libargon2-dev` previously having been named `libargon2-0-dev` in older distributions.

**Comment by DanWin** [comment]
Added it to the readme in a72733c2af97e817bd445d4cc54a7e38cedab49f
