### ISSUE TITLE
Confused on creating the mounts in /etc/fstab

### ISSUE THREAD

**Issue by RobCod** [DanWin/hosting#97]
In your read me it says to add a line to the /home and /, but there is no /home and / in the /etc/fstab file in the first place so im kind of getting confused by this.

Edit `/etc/fstab` and add the `noatime,usrjquota=aquota.user,jqfmt=vfsv1` option to the `/home` mountpoint and `noatime`to `/`. Then initialize quota:
```
mount -o remount /home
quotacheck -cMu /home
quotaon /home
```

**Comment by DanWin** [comment]
A typical fstab with this configuration looks like this:
```
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
UUID=a82edb37-d7a5-4ef2-a08a-6f1b0a1c20a8 /               ext4    defaults,noatime,discard 0       1
UUID=2a3d3781-f2aa-4691-b666-ea65128de8d3 /home           ext4    defaults,discard,noatime,usrjquota=aquota.user,jqfmt=vfsv1     0       2
```

It might be that you do not have a seperate hard drive or partition for `/` and `/home`. In that case, `/home` is part of your `/` mount and you should add the configuration options there instead, like this:
```
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
UUID=a82edb37-d7a5-4ef2-a08a-6f1b0a1c20a8 /               ext4    defaults,noatime,discard,,usrjquota=aquota.user,jqfmt=vfsv1 0       1
```

**Comment by RobCod** [comment]
Thank you danwin, I rei-installed debian with /home in a separate partition and I figured it out lol. thanks again hopfully i can get this working, I just wanna play around with it.
